# https://hub.docker.com/_/node
image: node:lts-alpine

# Cache modules in between jobs: https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - .npm/

variables:
  NODE_ENV: "production"
  PDC_VER: "2.11.3.1"

before_script:
- "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
- "wget -qO- https://github.com/jgm/pandoc/releases/download/${PDC_VER}/pandoc-${PDC_VER}-linux-amd64.tar.gz | sudo tar xvz --strip-components 1 -C /usr/local"
- npm ci --cache .npm --prefer-offline
- npm run build

test:
  stage: test
  script:
  - echo "Done"
  except:
  - main

pages:
  stage: build
  script:
  - apk add --update brotli
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
  only:
  - main
