# https://hub.docker.com/_/node
image: node:lts-alpine
# Cache modules in between jobs: https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - .npm/
    
before_script:
- apk add --update pandoc  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/
- npm ci --cache .npm --prefer-offline --production
- npm run build

test:
  stage: test
  script:
  - echo "Test complete"
  except:
  - main

pages:
  stage: deploy
  script:
  - apk add --update brotli
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
  only:
  - main
