name: Check markdown links by Lychee

on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 0 * * 1"  # Every Monday

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.1
        with:
          args: "--accept 200,204,429 --verbose --no-progress source/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: links
